name: Hack
on:
  workflow_dispatch:
  # workflow_call:
  # push:
  #   branches: [ "main" ]
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA_VALUE: ${{ github.event.head_commit.message }}
        run: echo $DATA_VALUE
      # avoid inline script for script injection attack
      #- run: echo ${{ github.event.head_commit.message }}

  # invoke-workflow-in-this-repo:
  # uses: ./.github/workflows/basic.yml # workflow_call
